# 1. Data Cleaning

In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv('creditcard.csv')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [37]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [38]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [39]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [40]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [41]:
df.duplicated().sum()

1081

In [42]:
df.drop_duplicates(keep='first',inplace=True)

In [43]:
df.duplicated().sum()

0

# 2. Data Analysis

In [44]:
legit = df[df.Class==0]
fraud = df[df.Class==1]

In [45]:
fraud.info()

<class 'pandas.core.frame.DataFrame'>
Index: 473 entries, 541 to 281674
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    473 non-null    float64
 1   V1      473 non-null    float64
 2   V2      473 non-null    float64
 3   V3      473 non-null    float64
 4   V4      473 non-null    float64
 5   V5      473 non-null    float64
 6   V6      473 non-null    float64
 7   V7      473 non-null    float64
 8   V8      473 non-null    float64
 9   V9      473 non-null    float64
 10  V10     473 non-null    float64
 11  V11     473 non-null    float64
 12  V12     473 non-null    float64
 13  V13     473 non-null    float64
 14  V14     473 non-null    float64
 15  V15     473 non-null    float64
 16  V16     473 non-null    float64
 17  V17     473 non-null    float64
 18  V18     473 non-null    float64
 19  V19     473 non-null    float64
 20  V20     473 non-null    float64
 21  V21     473 non-null    float64
 22  V22     473 non-null    float64
 23  V23     473 non-null    float64
 24  V24     473 non-null    float64
 25  V25     473 non-null    float64
 26  V26     473 non-null    float64
 27  V27     473 non-null    float64
 28  V28     473 non-null    float64
 29  Amount  473 non-null    float64
 30  Class   473 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 118.2 KB

In [46]:
legit['Amount'].describe()

count    283253.000000
mean         88.413575
std         250.379023
min           0.000000
25%           5.670000
50%          22.000000
75%          77.460000
max       25691.160000
Name: Amount, dtype: float64

In [47]:
fraud['Amount'].describe()

count     473.000000
mean      123.871860
std       260.211041
min         0.000000
25%         1.000000
50%         9.820000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [48]:
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94835.058093,0.013439,-0.009829,0.012853,-0.010440,0.006769,0.001251,0.010447,-0.002448,0.002613,...,-0.000489,-0.00115,-0.000160,0.000360,0.000393,-0.000301,0.000065,0.001409,0.000418,88.413575
1,80450.513742,-4.498280,3.405965,-6.729599,4.472591,-2.957197,-1.432518,-5.175912,0.953255,-2.522124,...,0.405043,0.46655,0.086639,-0.096464,-0.106643,0.040615,0.050456,0.213774,0.078270,123.871860

# 3. Data Preprocessing

In [49]:
legit_sam = legit.sample(n=473)

In [50]:
ndf = pd.concat([legit_sam,fraud],axis=0)

In [51]:
ndf.sample(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
159975,113061.0,2.081631,-0.147440,-1.493003,0.195269,0.060559,-0.951061,0.052668,-0.199313,1.003776,...,0.244019,0.770722,0.030798,0.711554,0.299321,-0.447321,-0.007236,-0.050668,1.00,0
126451,78009.0,1.193410,-0.238597,-0.112799,0.217285,-0.120394,-0.088863,0.038620,-0.069285,-1.647331,...,-0.591735,-1.353473,0.087435,-0.372437,0.337667,-0.636809,0.028479,0.019573,63.50,0
263877,161154.0,-3.387601,3.977881,-6.978585,1.657766,-1.100500,-3.599487,-3.686651,1.942252,-3.065089,...,1.043587,0.262189,-0.479224,-0.326638,-0.156939,0.113807,0.354124,0.287592,0.38,1
79883,58222.0,-1.322789,1.552768,-2.276921,2.992117,-1.947064,-0.480288,-1.362388,0.953242,-2.329629,...,0.614969,-0.195200,0.590711,-0.233378,-0.164285,-0.277498,0.428610,0.246394,270.00,1
136459,81714.0,0.980599,-0.454326,0.037759,-0.533485,-0.900934,-0.996548,-0.179907,-0.020604,1.338002,...,0.059333,0.111133,-0.202493,0.447991,0.559167,-0.665649,0.057894,0.063283,117.50,0

In [52]:
ndf['Class'].value_counts()

Class
0    473
1    473
Name: count, dtype: int64

In [53]:
ndf.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95932.221987,-0.017853,0.049877,0.029517,0.021129,0.115651,-0.005340,0.000929,-0.080639,-0.030750,...,0.010167,-0.010072,-0.026527,0.011883,0.017684,0.007117,-0.034018,-0.002607,-0.021705,79.065095
1,80450.513742,-4.498280,3.405965,-6.729599,4.472591,-2.957197,-1.432518,-5.175912,0.953255,-2.522124,...,0.405043,0.466550,0.086639,-0.096464,-0.106643,0.040615,0.050456,0.213774,0.078270,123.871860

In [54]:
x = ndf.drop(columns='Class',axis=1)
y = ndf['Class']

In [55]:
x.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
179740,124223.0,-6.297692,5.984341,-2.164875,-1.960356,0.482706,1.756912,-1.991790,-14.323990,4.597533,...,-0.423374,11.862637,-2.920234,1.546545,-0.880217,0.022193,-0.322547,0.284949,-0.887306,0.89
103714,68773.0,-1.923651,0.262193,1.630208,-2.365800,-1.780946,2.136082,-2.729967,-3.266325,-0.596900,...,-1.262208,3.617590,-0.994423,0.250248,-0.858056,0.017817,-0.186373,0.000419,-0.145680,28.90
95877,65507.0,-1.883138,1.657479,-0.573110,1.823742,-1.080387,0.470760,-1.045318,1.790921,-1.060831,...,-0.426289,0.237141,0.287152,0.079692,-0.267470,-0.159649,-0.178591,-0.738124,-0.315934,23.42
42732,41222.0,-0.798318,0.274479,0.999705,0.745266,1.779616,-0.700819,1.579767,-1.006390,-0.351450,...,0.046267,-0.134193,0.433417,0.077362,-0.430234,0.251328,-0.306781,-0.548793,-0.521128,1.59
189191,128295.0,1.700573,-0.970411,-0.439311,0.352379,-0.537545,0.676913,-0.809715,0.269653,1.071503,...,0.157392,0.113464,0.089634,0.135108,0.104884,-0.516446,0.138454,-0.027978,-0.018436,151.08

In [56]:
y.head()

179740    0
103714    0
95877     0
42732     0
189191    0
Name: Class, dtype: int64

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=42)

# 4. Model Training and Evaluation

In [59]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [60]:
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)

In [61]:
from sklearn.metrics import accuracy_score,precision_score

In [62]:
acc = accuracy_score(y_test,y_pred)
pre = precision_score(y_test,y_pred)

In [63]:
print(acc,pre)

0.9473684210526315 0.9775280898876404